./__unit-2_project/chipotle.ipynb-original
./__unit-2_project/imdb.ipynb-original
./__unit-3_project/linreg-knn-project.ipynb-original
./u1_s1_welcome-to-data-science/course_info_definitions.ipynb-original
./u1_s1_welcome-to-data-science/intro_to_python_fundamentals.ipynb-original
./u1_s2_your-development-environment/extra-materials/Command-Line/command-line.ipynb-original
./u1_s2_your-development-environment/extra-materials/Git-&-GitHub/Git-and-GitHub.ipynb-original
./u1_s2_your-development-environment/practice/ipynb_practice1.ipynb-original
./u1_s2_your-development-environment/practice/solution-code/ipynb_practice1-solution.ipynb-original
./u1_s2_your-development-environment/Your-Development-Environment.ipynb-original
./u1_s3_python-foundations/assets/originals/DataTypes/data-types-in-class.ipynb-original
./u1_s3_python-foundations/assets/originals/Iteratons-ControlFlow/iteration-control-flows-functions.ipynb-original
./u1_s3_python-foundations/assets/originals/Iteratons-ControlFlow/solution-code/iteration-control-flows-functions-solutions.ipynb-original
./u1_s3_python-foundations/practice/python-functions-lab-master/python-functions.ipynb-original
./u1_s3_python-foundations/practice/python-functions-lab-master/solution-code/python-functions-solutions.ipynb-original
./u1_s3_python-foundations/practice/python-movies_data_structures-lab-master/python-movies-lab.ipynb-original
./u1_s3_python-foundations/practice/python-movies_data_structures-lab-master/solution-code/python-movies-lab-solutions.ipynb-original
./u1_s3_python-foundations/practice/python-types_lists_dicts-lab-master/solution-code/types-lists-dictionaries-review-solutions.ipynb-original
./u1_s3_python-foundations/practice/python-types_lists_dicts-lab-master/types-lists-dictionaries-review.ipynb-original
./u1_s3_python-foundations/python-controlflow.ipynb-original
./u1_s3_python-foundations/python-dtypes.ipynb-original
./u1_s3_python-foundations/python-functions.ipynb-original
./u1_s3_python-foundations/python-movies-lab.ipynb-original
./u1_s3_python-foundations/solution-code/python-dtypes-controlflow-solution.ipynb-original
./u1_s3_python-foundations/solution-code/python-functions-solutions.ipynb-original
./u1_s3_python-foundations/solution-code/python-movies-lab-solutions.ipynb-original
./u1_s3_python-foundations/solution-code/types-lists-dictionaries-review-solutions.ipynb-original
./u1_s3_python-foundations/types-lists-dictionaries-review.ipynb-original
./u2_s5_exploratory-data-analysis/exploratory-data-analysis.ipynb-original
./u2_s5_exploratory-data-analysis/practice/eda-data_cleaning_intro-lab-master/pandas-cleaning-apply.ipynb-original
./u2_s5_exploratory-data-analysis/practice/eda-data_cleaning_intro-lab-master/solution-code/pandas-cleaning-apply-solution.ipynb-original
./u2_s5_exploratory-data-analysis/solution-code/exploratory-data-analysis-solution.ipynb-original
./u2_s6_experiments-hypothesis-tests/experiments-hypothesis-tests-new.ipynb-original
./u2_s6_experiments-hypothesis-tests/experiments-hypothesis-tests.ipynb-original
./u2_s6_experiments-hypothesis-tests/practice/eda-music_data_blogging-lab-master/eda-with-billboard-data-lab.ipynb-original
./u2_s6_experiments-hypothesis-tests/practice/eda-music_data_blogging-lab-master/solution-code/instructor-alternate/Ram_billboard-data-example-solution_Revised.ipynb-original
./u2_s6_experiments-hypothesis-tests/practice/eda-music_data_blogging-lab-master/solution-code/student-example-solution.ipynb-original
./u2_s6_experiments-hypothesis-tests/practice/eda-telecomm_group_project-lab-master/telecomm-eda-group-lab.ipynb-original
./u2_s6_experiments-hypothesis-tests/solution-code/.ipynb_checkpoints/experiments-hypothesis-tests_solutions-checkpoint.ipynb-original
./u2_s6_experiments-hypothesis-tests/solution-code/experiments-hypothesis-tests_solutions.ipynb-original
./u2_s7_visualizations/practice/python-data-viz-lab-new.ipynb-original
./u2_s7_visualizations/practice/python-data-viz-lab.ipynb-original
./u2_s7_visualizations/practice/solution-code/python-data-viz-lab-new-solutions.ipynb-original
./u2_s7_visualizations/practice/solution-code/python-data-viz-lab-solutions.ipynb-original
./u2_s7_visualizations/python-data-viz-slides.ipynb-original
./u2_s8_statistics-in-python/practice/python-descriptive_statistics_numpy-lab-master/describe-sales-data.ipynb-original
./u2_s8_statistics-in-python/practice/python-descriptive_statistics_numpy-lab-master/solution-code/describe-sales-data-solutions.ipynb-original
./u2_s8_statistics-in-python/practice/statistics-describing_data-lab-master/loading-and-describing-data.ipynb-original
./u2_s8_statistics-in-python/practice/statistics-describing_data-lab-master/solution-code/loading-and-describing-data-solution.ipynb-original
./u2_s8_statistics-in-python/solution-code/Statistics-Review-part-1-solution-new.ipynb-original
./u2_s8_statistics-in-python/solution-code/Statistics-Review-part-1-solution.ipynb-original
./u2_s8_statistics-in-python/Statistics-Review-part-1-new.ipynb-original
./u2_s8_statistics-in-python/Statistics-Review-part-1.ipynb-original
./u3_s10_linear-regression/linear_regression.ipynb-original
./u3_s10_linear-regression/practice/kobe-shots-made-regularization-lab.ipynb-original
./u3_s10_linear-regression/practice/linear_regression-review-lab-starter.ipynb-original
./u3_s10_linear-regression/practice/simple-linear-regression-sacramento.ipynb-original
./u3_s10_linear-regression/practice/solution-code/kobe-shots-made-regularization-lab-solutions.ipynb-original
./u3_s10_linear-regression/practice/solution-code/linear_regression-review-lab-solutions.ipynb-original
./u3_s10_linear-regression/practice/solution-code/simple-linear-regression-sacramento-solutions.ipynb-original
./u3_s10_linear-regression/solution-code/linear_regression-solution-new.ipynb-original
./u3_s10_linear-regression/solution-code/linear_regression-solution.ipynb-original
./u3_s11_train-test-split-and-bias-variance/bias-and-variance.ipynb-original
./u3_s11_train-test-split-and-bias-variance/practice/solution-code/train_test-cross_validation-lab-solutions.ipynb-original
./u3_s11_train-test-split-and-bias-variance/practice/train_test-cross_validation-lab.ipynb-original
./u3_s11_train-test-split-and-bias-variance/solution-code/bias-and-variance-solution.ipynb-original
./u3_s12_knn-classification/knn_with_sklearn.ipynb-original
./u3_s12_knn-classification/practice/knn_classification_imputation-lab.ipynb-original
./u3_s12_knn-classification/practice/NHL_classification_with_knn-lab.ipynb-original
./u3_s12_knn-classification/practice/solution-code/knn_classification_imputation-lab-solutions.ipynb-original
./u3_s12_knn-classification/practice/solution-code/NHL_classification_with_knn-lab-solutions.ipynb-original
./u3_s12_knn-classification/solution-code/knn_with_sklearn-solution.ipynb-original
./u3_s13_logistic-regression/extra-materials/e_log_examples.ipynb-original
./u3_s13_logistic-regression/extra-materials/titanic_confusion.ipynb-original
./u3_s13_logistic-regression/logistic-regression-starter.ipynb-original
./u3_s13_logistic-regression/practice/LogisticRegression-BankMarketing-Lab.ipynb-original
./u3_s13_logistic-regression/practice/MultiVariable_LogisticRegression-lab.ipynb-original
./u3_s13_logistic-regression/practice/predicting_evergreen_sites-lab.ipynb-original
./u3_s13_logistic-regression/practice/solution-code/LogisticRegression-BankMarketing-Lab-solutions.ipynb-original
./u3_s13_logistic-regression/practice/solution-code/MultiVariable_LogisticRegression-lab-solutions.ipynb-original
./u3_s13_logistic-regression/practice/solution-code/predicting_evergreen_sites-lab-solutions.ipynb-original
./u3_s13_logistic-regression/solution-code/logistic-regression-solution.ipynb-original
./u4_s15_getting-data-APIs/intro-to-web-services-apis.ipynb-original
./u4_s15_getting-data-APIs/practice/apis_practice-lab.ipynb-original
./u4_s15_getting-data-APIs/practice/solution-code/apis_practice-lab-solutions.ipynb-original
./u4_s15_getting-data-APIs/practice/solution-code/twitter_api_nlp-lab-solutions.ipynb-original
./u4_s15_getting-data-APIs/practice/solution-code/webscraping_selenium-lab-solutions.ipynb-original
./u4_s15_getting-data-APIs/practice/twitter_api_nlp-lab.ipynb-original
./u4_s15_getting-data-APIs/practice/webscraping_selenium-lab.ipynb-original
./u4_s15_getting-data-APIs/solution-code/webscraping-in-class-solutions.ipynb-original
./u4_s15_getting-data-APIs/webscraping-in-class.ipynb-original
./u4_s16_natural-language-processing/extra-materials/bayes_theorem_iris.ipynb-original
./u4_s16_natural-language-processing/natural-language-processing.ipynb-original
./u4_s16_natural-language-processing/practice/intro_to_nlp-lab.ipynb-original
./u4_s16_natural-language-processing/practice/nlp_review-lab.ipynb-original
./u4_s16_natural-language-processing/practice/sentiment_analysis-lab.ipynb-original
./u4_s16_natural-language-processing/practice/solution-code/intro_to_nlp-lab-solutions.ipynb-original
./u4_s16_natural-language-processing/practice/solution-code/nlp_review-lab-solutions.ipynb-original
./u4_s16_natural-language-processing/practice/solution-code/sentiment_analysis-lab-solutions.ipynb-original
./u4_s16_natural-language-processing/practice/solution-code/topic_modeling_lda-codealong-solutions.ipynb-original
./u4_s16_natural-language-processing/practice/topic_modeling_lda-codealong.ipynb-original
./u4_s17_time-series/01_time_series.ipynb-original
./u4_s17_time-series/02_rolling_statistics.ipynb-original
./u4_s17_time-series/03_autocorrelation.ipynb-original
./u4_s17_time-series/04_decomposition.ipynb-original
./u4_s17_time-series/05_independent_practice.ipynb-original
./u4_s17_time-series/06_bonus_time_series_models.ipynb-original
./u4_s17_time-series/solution-code/01_time_series_solutions.ipynb-original
./u4_s17_time-series/solution-code/02_rolling_statistics_solutions.ipynb-original
./u4_s17_time-series/solution-code/03_autocorrelation_solutions.ipynb-original
./u4_s17_time-series/solution-code/04_decomposition_solutions.ipynb-original
./u4_s17_time-series/solution-code/05_independent_practice_solutions.ipynb-original
./u4_s18_decision-trees/decision_trees.ipynb-original
./u4_s18_decision-trees/ensembles_random_forests.ipynb-original
./u4_s18_decision-trees/practice/build_a_random_forest-codealong.ipynb-original
./u4_s18_decision-trees/practice/solution-code/build_a_random_forest-codealong-solutions.ipynb-original
